version: 2.1

# List of all jobs.
jobs:
  # Build and test the project the project.
  build_and_test:
    docker:
      - image: circleci/ruby:latest
    steps:
      # Update the project.
      - checkout

      # Install Rust.
      - run:
          name: Install Rust
          command: |
            test -d /usr/local/cargo || curl https://sh.rustup.rs -sSf | sh -s -- -y

      # Install `just` used to manage the project.
      - run:
          name: Install just
          command: |
            export PATH="$HOME/.cargo/bin:$PATH"
            test -f $HOME/.cargo/bin/just || cargo install just

      # Compile the Ruby extension.
      - run:
          name: Compile the Ruby extension
          command: |
            export PATH="$HOME/.cargo/bin:$PATH"
            just build

      # Run the extension test suites.
      - run:
          name: Test the extension
          command: |
            export PATH="$HOME/.cargo/bin:$PATH"
            gem install bundler
            just test


# List of workflows.
workflows:
  version: 2

  # The build workflow.
  build:
    jobs:
      # Run the `build_and_test` job for all branches and all tags.
      - build_and_test:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
